# Generated by Django 4.2.26 on 2025-11-06 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_meal_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sellerverificationapplication',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AddField(
            model_name='sellerverificationapplication',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal notes for admins reviewing this application'),
        ),
        migrations.AddField(
            model_name='sellerverificationapplication',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerverificationapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sellerverificationapplication',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
