# Generated by Django 5.0 on 2025-11-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_reservation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="meals/"),
        ),
    ]
