# Generated by Django 5.0 on 2025-12-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="dietary_tags",
            field=models.CharField(
                choices=[
                    ("vegetarian", "Vegetarian"),
                    ("vegan", "Vegan"),
                    ("gluten_free", "Gluten-Free"),
                    ("dairy_free", "Dairy-Free"),
                    ("halal", "Halal"),
                    ("kosher", "Kosher"),
                    ("nut_free", "Nut-Free"),
                    ("none", "No Restrictions"),
                ],
                default="none",
                help_text="Select the primary dietary category for this meal",
                max_length=100,
            ),
        ),
    ]
