# Generated by Django 5.0 on 2025-12-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_meal_nutrition_info_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="allergens",
            field=models.TextField(
                blank=True,
                help_text="Comma-separated list of allergens (auto-generated)",
            ),
        ),
        migrations.AddField(
            model_name="meal",
            name="calories",
            field=models.IntegerField(
                blank=True, help_text="Calories per serving (auto-generated)", null=True
            ),
        ),
        migrations.AddField(
            model_name="meal",
            name="carbs",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Carbohydrates in grams (auto-generated)",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="meal",
            name="fat",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Fat in grams (auto-generated)",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="meal",
            name="protein",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Protein in grams (auto-generated)",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="meal",
            name="nutrition_info",
            field=models.TextField(
                blank=True, help_text="Additional nutrition notes or message from API"
            ),
        ),
    ]
